// Generate a header file for super fast lookup of a char number as a string
// 
// You should shove the output into a '.inl' file (for 'inline')


#include <stdio.h>

int main(int argc, char const *argv[])
{
  printf("// THIS FILE WAS AUTOMATICALLY GENERATED BY generateColorLookup.cpp\n");
  
  // Up to the user to wrap this code in a 2d array declaration, ex:

  //printf("#pragma once\n\n");
  //printf("const char ColorCodeLookup[][] = {\n");

  for(int i = 0; i < 256; ++i)
    printf("\"%03d\", ", i);

  //printf("\n};\n");

  return 0;
}
